version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev-ms
    environment:
      POSTGRES_DB: dev_ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: harianbu@3
    ports:
      - "5433:5432"
    networks:
      - spring-dev-ms-net
    volumes:
      - postgres-data:/var/lib/dev/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-dev-ms
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    networks:
      - spring-dev-ms-net
    volumes:
      - pgadmin-data:/var/lib/dev
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: mongo-dev-ms
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: hariharan
      MONGO_INITDB_ROOT_PASSWORD: harianbu
    networks:
      - spring-dev-ms-net
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-dev-ms
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hariharan
      ME_CONFIG_MONGODB_ADMINPASSWORD: harianbu
      ME_CONFIG_MONGODB_SERVER: mongo-dev-ms
    networks:
      - spring-dev-ms-net
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-dev
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - spring-dev-ms-net
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-dev-ms
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - spring-dev-ms-net
    restart: unless-stopped

networks:
  spring-dev-ms-net:
    driver: bridge

volumes:
  mongo-data:
  postgres-data:
  pgadmin-data:
